name: "Test kfx using KinD"
on: [pull_request, push]

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - uses: engineerd/setup-kind@v0.3.0
      with:
        name: "kfx-k8s"
        version: "v0.7.0"
        config: "kind/kind-config.yaml"
    
    - name: KinD Cluster Check
      run: |
        kubectl cluster-info
        kubectl get pods -n kube-system
    
    - uses: actions/setup-go@v2-beta
      with:
        go-version: '^1.14.1'
      env:
        GOPATH: /home/runner/work/kfx/kfx
    - run: |
        ${GITHUB_WORKSPACE}/kind-smoketest.sh
