name: "Test kfx using KinD"
on: [pull_request, push]

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: engineerd/setup-kind@v0.3.0
      with:
        name: "kfx-k8s"
        version: "v0.7.0"
        config: "kind/kind-config.yaml"
    
    - name: KinD Cluster Check
      run: |
        kubectl cluster-info
        kubectl get pods -n kube-syste
    
    - uses: actions/setup-go@v2-beta
      with:
        go-version: '^1.13.1'
    - run: |
        go version
        mkdir -p ${GOPATH}/src/github.com/CiscoAI/kfx/
        cp -r . ${GOPATH}/src/github.com/CiscoAI/kfx/
        cd ${GOPATH}/src/github.com/CiscoAI/kfx/
        ./kind-smoketest.sh

